version: 1

    name: watchhive-api
    env: node
    plan: free
    region: singapore
    buildCommand: cd server && npm install && npm run build && npx prisma generate
    startCommand: cd server && npx prisma migrate deploy && npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: watchhive-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: watchhive-cache
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: TMDB_API_KEY
        sync: false
      - key: FRONTEND_URL
        fromService:
          type: static
          name: watchhive-client
          property: url


static_sites:
  # Frontend Client
  - name: watchhive-client
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: watchhive-api
          property: url
        suffix: /api/v1


kv:
  - name: watchhive-cache
    plan: free


databases:
  - name: watchhive-db
    plan: free
    region: singapore

